import { StyleSheet } from "react-native";

export const GRADIENT = {
  top: "#FFE0C2",
  mid: "#FFF0E4",
  bottom: "#FFFFFF",
};

const C = {
  bg: "#FFFFFF",
  bgCard: "#FFFAF6",
  bgCardAlt: "#FFF5EC",
  bgGray: "#F5EDE0",

  textDark: "#0F1A22",
  text: "#1C2B36",
  textSec: "#7A8A98",
  textLight: "#B0BECA",
  textOnDark: "#FFFFFF",

  primary: "#F47B20",
  primaryDark: "#D96A12",
  primaryLight: "#FFF3E8",
  primaryMuted: "#FFE0C2",

  border: "#F0DED0",
  borderLight: "#FAF0E8",
};

export const mealDetailStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: C.bg,
  },

  scrollView: {
    flex: 1,
  },
  contentContainer: {
    paddingBottom: 48,
  },

  imageContainer: {
    width: "100%",
    height: 260,
    backgroundColor: C.bgCardAlt,
  },
  mealImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  imageGradientOverlay: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    height: 160,
  },
  imagePlaceholder: {
    width: "100%",
    height: "100%",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: C.bgCardAlt,
  },
  imagePlaceholderIcon: {
    width: 96,
    height: 96,
    borderRadius: 32,
    backgroundColor: C.primaryLight,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 2,
    borderColor: C.primaryMuted,
    shadowColor: "#F47B20",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.2,
    shadowRadius: 16,
    elevation: 6,
  },

  heroTextOverlay: {
    position: "absolute",
    bottom: 52,
    left: 20,
    right: 20,
  },
  heroMealName: {
    fontSize: 22,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: -0.8,
    textShadowColor: "rgba(0,0,0,0.35)",
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 8,
    marginBottom: 6,
  },
  heroTimeRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 5,
  },
  heroTimeText: {
    fontSize: 13,
    color: "rgba(255,255,255,0.82)",
    fontWeight: "500",
  },

  backButton: {
    position: "absolute",
    left: 16,
    zIndex: 20,
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: "rgba(255,255,255,0.95)",
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.15,
    shadowRadius: 8,
    elevation: 6,
    borderWidth: 1,
    borderColor: "rgba(240,222,208,0.8)",
  },

  pullUpCard: {
    backgroundColor: C.bg,
    marginHorizontal: 0,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
    marginTop: -32,
    paddingTop: 16,
    paddingHorizontal: 20,
    paddingBottom: 2,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.06,
    shadowRadius: 16,
    elevation: 10,
  },
  pullUpHandle: {
    width: 40,
    height: 4,
    borderRadius: 2,
    backgroundColor: C.border,
    alignSelf: "center",
    marginBottom: 16,
  },

  caloriesCard: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.primary,
    marginHorizontal: 20,
    marginBottom: 14,
    padding: 14,
    borderRadius: 22,
    shadowColor: "#F47B20",
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 6,
  },
  caloriesIconContainer: {
    width: 46,
    height: 46,
    borderRadius: 16,
    backgroundColor: "rgba(255,255,255,0.18)",
    alignItems: "center",
    justifyContent: "center",
    marginRight: 14,
    borderWidth: 1.5,
    borderColor: "rgba(255,255,255,0.25)",
  },
  caloriesInfo: {
    flex: 1,
  },
  caloriesLabel: {
    fontSize: 10,
    fontWeight: "700",
    color: "rgba(255,255,255,0.75)",
    textTransform: "uppercase",
    letterSpacing: 1.2,
    marginBottom: 2,
  },
  caloriesValue: {
    fontSize: 30,
    fontWeight: "800",
    color: "#FFFFFF",
    letterSpacing: -1.2,
    lineHeight: 33,
  },
  caloriesUnit: {
    fontSize: 13,
    color: "rgba(255,255,255,0.75)",
    fontWeight: "600",
  },
  caloriesBadge: {
    backgroundColor: "rgba(255,255,255,0.2)",
    paddingHorizontal: 9,
    paddingVertical: 3,
    borderRadius: 20,
    alignSelf: "flex-start",
    marginTop: 6,
  },
  caloriesBadgeText: {
    fontSize: 10,
    fontWeight: "700",
    color: "#FFFFFF",
    letterSpacing: 0.3,
  },

  section: {
    paddingHorizontal: 20,
    marginTop: 16,
  },
  sectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 8,
    marginBottom: 10,
  },
  sectionHeaderLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  sectionDot: {
    width: 6,
    height: 6,
    borderRadius: 3,
    backgroundColor: C.primary,
  },
  sectionTitle: {
    fontSize: 11,
    fontWeight: "800",
    color: C.primary,
    textTransform: "uppercase",
    letterSpacing: 1.4,
  },

  macroGrid: {
    flexDirection: "row",
    gap: 8,
  },
  macroCard: {
    flex: 1,
    backgroundColor: C.bgCard,
    borderRadius: 16,
    paddingTop: 10,
    paddingBottom: 10,
    paddingHorizontal: 8,
    alignItems: "center",
    shadowColor: "#F47B20",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.06,
    shadowRadius: 8,
    elevation: 2,
    borderWidth: 1,
    borderColor: C.border,
    overflow: "hidden",
  },
  macroCardAccent: {
    width: 40,
    height: 40,
    borderRadius: 13,
    marginBottom: 12,
    alignItems: "center",
    justifyContent: "center",
    opacity: 0.18,
  },
  macroIcon3d: {
    width: 30,
    height: 30,
    marginBottom: 4,
  },
  macroLabel: {
    fontSize: 9,
    fontWeight: "700",
    color: C.textSec,
    textTransform: "uppercase",
    letterSpacing: 0.6,
    marginBottom: 2,
  },
  macroValue: {
    fontSize: 16,
    fontWeight: "800",
    color: C.textDark,
    letterSpacing: -0.3,
  },
  macroUnit: {
    fontSize: 11,
    fontWeight: "600",
    color: C.textSec,
  },

  // Compact 3-across chip grid — mirrors macroGrid so calories/macros/extra
  // nutrients read as one consistent "stats" tier above the ingredients list.
  nutrientsList: {
    flexDirection: "row",
    gap: 8,
  },
  nutrientRow: {
    flex: 1,
    flexDirection: "column",
    alignItems: "center",
    backgroundColor: C.bgCard,
    borderRadius: 16,
    paddingVertical: 10,
    paddingHorizontal: 6,
    borderWidth: 1,
    borderColor: C.border,
  },
  nutrientLeft: {
    flexDirection: "column",
    alignItems: "center",
    gap: 2,
  },
  nutrientIcon3d: {
    width: 30,
    height: 30,
    marginBottom: 4,
  },
  nutrientLabel: {
    fontSize: 8,
    fontWeight: "700",
    color: C.textSec,
    textTransform: "uppercase",
    letterSpacing: 0.4,
    textAlign: "center",
  },
  nutrientValue: {
    fontSize: 14,
    fontWeight: "800",
    color: C.textDark,
    letterSpacing: -0.3,
  },

  aiNotice: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: C.primaryLight,
    padding: 16,
    borderRadius: 18,
    gap: 12,
    borderWidth: 1,
    borderColor: C.primaryMuted,
    borderLeftWidth: 4,
    borderLeftColor: C.primary,
  },
  aiNoticeBadge: {
    width: 34,
    height: 34,
    borderRadius: 10,
    backgroundColor: C.primaryMuted,
    alignItems: "center",
    justifyContent: "center",
    flexShrink: 0,
  },
  aiNoticeText: {
    flex: 1,
    fontSize: 12,
    fontWeight: "500",
    color: C.textSec,
    lineHeight: 18,
  },

  errorContainer: {
    flex: 1,
    alignItems: "center",
    justifyContent: "center",
    padding: 32,
  },
  errorText: {
    fontSize: 16,
    fontWeight: "600",
    color: C.textLight,
  },

  infoCard: {
    backgroundColor: C.bgCard,
    padding: 22,
    marginHorizontal: 16,
    borderRadius: 28,
    marginTop: -40,
    marginBottom: 12,
    shadowColor: "#F47B20",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.13,
    shadowRadius: 24,
    elevation: 8,
    borderWidth: 1,
    borderColor: C.border,
  },
  mealName: {
    fontSize: 26,
    fontWeight: "800",
    color: C.textDark,
    marginBottom: 10,
    letterSpacing: -0.5,
  },
  timeContainer: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
  },
  timeText: {
    fontSize: 13,
    color: C.textLight,
    fontWeight: "500",
  },
  nutrientAccentBar: {
    width: 4,
    height: 36,
    borderRadius: 4,
    backgroundColor: C.primary,
    marginRight: 4,
  },
  macroIcon: {
    width: 48,
    height: 48,
    borderRadius: 15,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 10,
  },
  ingredientsHeader: {
    flexDirection: "row",
    alignItems: "center",
    gap: 10,
    marginBottom: 16,
  },
  ingredientCountPill: {
    borderRadius: 999,
    paddingHorizontal: 9,
    paddingVertical: 2,
    borderWidth: 1,
    borderColor: C.primaryMuted,
  },
  ingredientCountText: {
    fontSize: 11,
    fontWeight: "800",
    color: C.primary,
    textTransform: "uppercase",
    letterSpacing: 0.8,
  },
  ingredientCountUnit: {
    textTransform: "none",
  },
  ingredientsContainer: {
    backgroundColor: C.bgCard,
    borderRadius: 22,
    paddingHorizontal: 16,
    paddingVertical: 4,
    shadowColor: "#F47B20",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.09,
    shadowRadius: 14,
    elevation: 4,
    borderWidth: 1,
    borderColor: C.border,
    position: "relative",
  },
  ingredientsRecalcOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    zIndex: 10,
    borderRadius: 22,
    backgroundColor: "rgba(255,250,246,0.9)",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    gap: 8,
  },
  ingredientsRecalcText: {
    fontSize: 13,
    fontWeight: "600",
    color: C.textSec,
  },
  // One ingredient per row: name on the left, grams pill on the right
  ingredientRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: C.borderLight,
  },
  ingredientLeft: {
    flexDirection: "row",
    alignItems: "center",
    gap: 12,
    flex: 1,
    paddingRight: 12,
  },
  ingredientDot: {
    width: 9,
    height: 9,
    borderRadius: 5,
    backgroundColor: C.primary,
  },
  ingredientName: {
    flex: 1,
    fontSize: 15,
    fontWeight: "600",
    color: C.textDark,
    letterSpacing: -0.2,
  },
  ingredientGramPill: {
    backgroundColor: C.primaryLight,
    paddingHorizontal: 12,
    paddingVertical: 5,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: C.primaryMuted,
  },
  // Swapped in during edit mode — matches the screen background so the
  // pill reads as an editable field rather than a static value.
  ingredientGramPillEditable: {
    backgroundColor: C.bg,
    borderColor: C.border,
    borderStyle: "dashed",
  },
  ingredientGramText: {
    fontSize: 14,
    fontWeight: "700",
    color: C.primary,
    letterSpacing: -0.2,
  },
  // Empty state
  noIngredientsWrap: {
    alignItems: "center",
    paddingVertical: 18,
    gap: 8,
  },
  noIngredientsEmoji: {
    fontSize: 26,
  },
  noIngredientsText: {
    fontSize: 13.5,
    color: C.textSec,
    fontWeight: "600",
    textAlign: "center",
  },
  nutrientIconSmall: {
    width: 40,
    height: 40,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
  },

  // ─── Ingredient editing ───
  ingredientEditButton: {
    width: 40,
    height: 40,
    alignItems: "center",
    justifyContent: "center",
  },
  ingredientDeleteButton: {
    width: 26,
    height: 26,
    borderRadius: 13,
    alignItems: "center",
    justifyContent: "center",
    marginLeft: 8,
  },

  // ─── Ingredient form modal — mirrors the Data screen's update modal ───
  modalOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(15, 26, 34, 0.55)",
  },
  modalContent: {
    backgroundColor: C.bgCard,
    borderRadius: 24,
    padding: 22,
    width: "85%",
    maxWidth: 340,
    shadowColor: "#F47B20",
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.12,
    shadowRadius: 22,
    elevation: 10,
    borderWidth: 1,
    borderColor: C.border,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "700",
    marginBottom: 4,
    color: C.textDark,
    letterSpacing: -0.3,
  },
  modalSubtitle: {
    fontSize: 13,
    color: C.textSec,
    marginBottom: 20,
    lineHeight: 18,
    fontWeight: "400",
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 12,
    color: C.textSec,
    fontWeight: "600",
    marginBottom: 6,
  },
  textInput: {
    borderWidth: 1,
    borderColor: C.border,
    borderRadius: 14,
    paddingVertical: 12,
    paddingHorizontal: 14,
    fontSize: 15,
    color: C.textDark,
    fontWeight: "500",
    backgroundColor: C.bgCardAlt,
  },
  textInputFocused: {
    borderColor: C.primary,
    backgroundColor: C.primaryLight,
  },
  modalButtonRow: {
    flexDirection: "row",
    gap: 10,
    marginTop: 6,
  },
  modalCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 50,
    backgroundColor: C.bgGray,
    alignItems: "center",
  },
  modalCancelButtonText: {
    color: C.textSec,
    fontSize: 14,
    fontWeight: "600",
  },
  modalConfirmButton: {
    flex: 1,
    backgroundColor: C.primary,
    paddingVertical: 14,
    borderRadius: 50,
    alignItems: "center",
    shadowColor: "#D96A12",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.25,
    shadowRadius: 10,
    elevation: 5,
  },
  modalConfirmButtonText: {
    color: C.textOnDark,
    fontSize: 14,
    fontWeight: "600",
    letterSpacing: 0.2,
  },
  modalLoadingContainer: {
    padding: 20,
    alignItems: "center",
  },
  modalLoadingText: {
    marginTop: 12,
    fontSize: 14,
    color: C.textSec,
    fontWeight: "600",
  },
});
