import { StyleSheet } from "react-native";

export const homeStyles = StyleSheet.create({
  body: {
    padding: 10,
    backgroundColor: "white",
    height: "100%",
    marginInline: 8,
  },
  heading: {
    display: "flex",
    flexDirection: "row",
    marginBottom: 10,
  },
  logo: {
    width: 42,
    height: 42,
    margin: 0,
    marginLeft: -7,
  },
  logoName: {
    fontWeight: "bold",
    fontSize: 20,
    marginTop: 8,
  },
  dailyDetails: {
    marginTop: 7,
    borderRadius: 10,
  },
  userProfile: {
    display: "flex",
    flexDirection: "row",
    alignItems: "center",
    height: 70,
    justifyContent: "space-between",
    padding: 10,
    borderRadius: 10,
    backgroundColor: "#FAF9F6",
  },
  progressContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: 200,
    marginVertical: 10,
    backgroundColor: "#FAF9F6",
    borderRadius: 10,
    padding: 10,
  },
  progressLabel: {
    marginTop: 10,
    fontSize: 14,
    color: "#666",
  },
  macroNutrients: {
    display: "flex",
    flexDirection: "row",
    width: "100%",
    marginVertical: 10,
    gap: 8,
  },
  nutrientsCard: {
    display: "flex",
    flexDirection: "column",
    height: 180,
    flex: 1,
    borderRadius: 10,
    padding: 8,
    backgroundColor: "#FAF9F6",
    justifyContent: "center",
    alignItems: "center",
  },
  nutrientsLabel: {
    fontSize: 12,
    color: "#666",
    marginBottom: 8,
  },
  nutrientsValue: {
    fontSize: 32,
    fontWeight: "bold",
    color: "#333",
  },
  nutrientsRemaining: {
    fontSize: 11,
    color: "#999",
    marginTop: 4,
  },
  button: {
    backgroundColor: "black",
    padding: 8,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    width: 40,
    height: 40,
  },
  plus: {
    color: "#fff",
    fontSize: 20,
    fontWeight: "normal",
  },
  impDetails: {
    fontSize: 25,
    fontWeight: "bold",
    marginRight: 10,
  },
  notesDetails: {
    fontSize: 12,
  },
  modalOverlay: {
    flex: 1,
    justifyContent: "flex-end",
    backgroundColor: "rgba(0,0,0,0.5)",
  },
  modalContent: {
    backgroundColor: "white",
    borderTopLeftRadius: 20,
    borderTopRightRadius: 20,
    paddingTop: 20,
    paddingBottom: 30,
    paddingHorizontal: 20,
  },
  modalHandle: {
    alignItems: "center",
    marginBottom: 10,
  },
  modalHandleBar: {
    width: 40,
    height: 4,
    backgroundColor: "#ccc",
    borderRadius: 2,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "700",
    marginBottom: 20,
    textAlign: "center",
  },
  cancelButton: {
    marginTop: 20,
    paddingVertical: 12,
    borderRadius: 8,
    backgroundColor: "#f0f0f0",
  },
  cancelButtonText: {
    textAlign: "center",
    fontSize: 16,
    fontWeight: "600",
    color: "#333",
  },
  loadingOverlay: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0,0,0,0.7)",
  },
  loadingContainer: {
    backgroundColor: "white",
    padding: 30,
    borderRadius: 12,
    alignItems: "center",
  },
  loadingText: {
    marginTop: 15,
    fontSize: 16,
    color: "#333",
  },
  // Meal History Styles
  mealHistorySection: {
    marginTop: 15,
    marginBottom: 20,
  },
  mealItem: {
    backgroundColor: "#FAF9F6",
    borderRadius: 12,
    marginBottom: 12,
    overflow: "hidden",
  },
  mealItemHeader: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    justifyContent: "space-between",
  },
  mealImageContainer: {
    width: 70,
    height: 70,
    borderRadius: 8,
    marginRight: 12,
    overflow: "hidden",
    backgroundColor: "#E0E0E0",
  },
  mealImage: {
    width: "100%",
    height: "100%",
    resizeMode: "cover",
  },
  mealHeaderInfo: {
    flex: 1,
    justifyContent: "center",
  },
  mealTime: {
    fontSize: 13,
    color: "#999",
    marginBottom: 4,
  },
  mealCalories: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
  },
  mealArrow: {
    fontSize: 20,
    color: "#2ecc71",
    fontWeight: "bold",
  },
  mealDetailsContainer: {
    backgroundColor: "white",
    paddingHorizontal: 12,
    paddingBottom: 12,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  mealDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 8,
    borderBottomWidth: 0.5,
    borderBottomColor: "#E0E0E0",
  },
  mealDetailLabel: {
    fontSize: 12,
    color: "#666",
    fontWeight: "500",
  },
  mealDetailValue: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
  },
  emptyMealText: {
    fontSize: 14,
    color: "#999",
    textAlign: "center",
    paddingVertical: 20,
  },
});
